INSERT INTO comments (comment, user_id, resource_id) VALUES ('Every time I chop onion I can''t stop crying. Tips anyone??', 3, 4);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Who here is also a Taurus?', 2, 2);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('WOW Knitting is so cooooooooolllll!', 3, 1);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('No Way Knitting is lame O', 7, 1);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('How dare you sir!!!!', 1, 1);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('You Take it back right now, knitting has taken me through some dark places', 8, 1);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Everybody wants to be a rockstar!', 1, 7);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Rockstars are corrupting our children ??!?!?!?', 1, 7);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('OMG!!! I cant believe this', 2, 1);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Great Article thanks for sharing', 2, 2);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Defintely going to save this for later', 3, 3);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('WOW!!!!', 3, 4);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Great share!!', 3, 5);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('love this!', 5, 6);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('I can not handle this', 5, 7);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('hahahha!', 5, 8);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('^ LOL', 5, 9);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('im so confused at this???', 6, 4);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Please delete this off your resource-DO NOT LIKE', 6, 4);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('WOW!! OMG', 6, 4);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('This is shocking', 6, 10);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('I cant believe this', 7, 10);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('????', 7, 4);
INSERT INTO comments (comment, user_id, resource_id) VALUES (' wow how did you find this!!?', 7, 6);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Thanks Karen for the share!', 8, 9);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('wowwww', 3, 3);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Please send me this to my gmail!', 2, 21);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Wow we have the same interests ', 5, 30);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('DEAN!!!!!!!! DONT DO THIS', 7, 24);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('WHAT ABOUT KRISTINA?', 8, 24);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('I LOVE HIM AWWWWW', 8, 25);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Great share!!', 10, 24);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('love this!', 11, 23);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('i hate this', 2, 22);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('hahahha!', 5, 21);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('this is not funny', 4, 10);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('I wish I did not have to see this on my timeline', 12, 11);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('EWWWWWWWWW', 8, 13);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('this is so surprising', 2, 14);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('I am going to bed now, this is too much for me!', 10, 19);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('NOOOOOOOOO', 6, 20);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('THANK YOU!!!!', 11, 29);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Hello - where did you even find this???', 2, 5);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Amazing find', 1, 9);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Amazing! Can you make a video on how to make your own??', 5, 8);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Super helpful! Can''t wait to practice', 2, 8);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('I wish he was my triangle teacher!', 3, 8);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Love this movie!', 6, 16);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Thanks! So helpful', 5, 13);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Don''t make promises you cant''t keep! Ha!', 2, 13);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Bzzzzzzzz', 2, 12);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Bzzzzzzzz', 5, 12);
INSERT INTO comments (comment, user_id, resource_id) VALUES ('Mac n Screams!', 5, 2);